# Generated by Django 3.2.7 on 2022-04-18 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_user_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Themes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('light', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='theme',
            field=models.TextField(default='darkStyle.css'),
        ),
    ]
